name: my_portfolio
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.1.0
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  intl: any
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5
  freezed: ^3.1.0
  freezed_lint: ^0.0.10
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

  shaders:
    - shaders/minimal_background.frag
